# Generated by Django 2.2.6 on 2019-10-17 01:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TODO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='')),
                ('due_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('state', models.CharField(choices=[('todo', 'Todo'), ('in_progress', 'In progress'), ('done', 'Done')], default='todo', max_length=11)),
            ],
        ),
    ]
